### PR TITLE
Same minor bug fix #4036. For release/3.1.1

### LINKED ISSUE #4036: Invalid JsonWebKey when it is ECDsaSecurityKey at DiscoveryResponseGenerator
**We can only help you if you are on the latest version. Either use the latest 2.x or 3.x**
Latest version: 3.1

### Issue / Steps to reproduce the problem
At AddSigningCredentials is possible to pass as argument some SecurityKeys (RSA, ECDsa...).

If you create a ECDsaSecurity and convert it as JsonWebKey, then IdentityServer4 dont get `crv` parameter from JsonWebKey.

At our prod servers we decided to keep all SecurityKeys in `Microsoft.IdentityModel.Tokens.JsonWebKey` form. So it's easily to manage and store them. But we caught this bug in our Production server when we changed from PS256 to ES256.

jwks_uri endpoint:
image
1 - ECDsaSecurityKey
2 - RSA...
3 - JsonWebToken with ECDsaSecurityKey params.

Bug at `DiscoveryResponseGenerator.cs`:

``` c#
// line 474
                else if (key.Key is JsonWebKey jsonWebKey)
                {
                    var webKey = new Models.JsonWebKey
                    {
                        kty = jsonWebKey.Kty,
                        use = jsonWebKey.Use ?? "sig",
                        kid = jsonWebKey.Kid,
                        x5t = jsonWebKey.X5t,
                        e = jsonWebKey.E,
                        n = jsonWebKey.N,
                        x5c = jsonWebKey.X5c?.Count == 0 ? null : jsonWebKey.X5c.ToArray(),
                        alg = jsonWebKey.Alg,
                         // Maybe here should have crv:
                        x = jsonWebKey.X,
                        y = jsonWebKey.Y
                    };

                    webKeys.Add(webKey);
                }
```

### PR DESCRIPTION
**Pull request by brunohbrito**
**What issue does this PR address?**
Bug fix for #4036

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/IdentityServer/IdentityServer4/blob/master/.github/CONTRIBUTING.md)
- [x] Unit Tests for the changes have been added (for bug fixes / features)

**Other information**:
In my environment 6 tests are failing, right after I build first time, before any modification. May I have done something wrong?

### CODE REVIEW

**Comment by leastprivilege** [comment]
try again - some certs were expired

**Comment by leastprivilege** [comment]
thanks!

File: src/IdentityServer4/src/Configuration/CryptoHelper.cs [hunk 1]
```diff
@@ -137,6 +137,12 @@ internal static bool IsValidCurveForAlgorithm(ECDsaSecurityKey key, string algor
 
             return true;
         }
+        internal static bool IsValidCrvValueForAlgorithm(string crv)
+        {
+            return crv == JsonWebKeyECTypes.P256 ||
+                   crv == JsonWebKeyECTypes.P384 ||
+                   crv == JsonWebKeyECTypes.P521;
```
Comment (vanbukin) [inline src/IdentityServer4/src/Configuration/CryptoHelper.cs]: Maybe JsonWebKeyECTypes.P512 instead of JsonWebKeyECTypes.P521?

Comment (brunohbrito) [reply src/IdentityServer4/src/Configuration/CryptoHelper.cs]: Hi @vanbukin,

Good question, because RFC 7518 specify P256, P384 and P521 [RFC 7518 - Section 6.2.1.1](https://tools.ietf.org/html/rfc7518#section-6.2.1.1)

Comment (vanbukin) [reply src/IdentityServer4/src/Configuration/CryptoHelper.cs]: This might be helpful for someone https://crypto.stackexchange.com/a/6221
